name: Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use node
        uses: actions/setup-node@v2.5.0
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
