name: Build & Deploy

on:
  - push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Use node
        uses: actions/setup-node@v3.8.1
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - name: Install
        run: npm install
      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: public
          clean: true
          dry-run: ${{ github.ref != 'refs/heads/main' }}
