name: Build & Deploy

on:
  - push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Use node
        uses: actions/setup-node@v4.0.4
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - name: Install
        run: npm install
      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          branch: gh-pages
          folder: public
          clean: true
          dry-run: ${{ github.ref != 'refs/heads/main' }}
