name: Build & Deploy

on:
  - push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Use node
        uses: actions/setup-node@v3.3.0
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - name: Install
        run: npm install
      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          branch: gh-pages
          folder: public
          clean: true
          dry-run: ${{ github.ref != 'refs/heads/main' }}
